default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-xml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix", "lf"]
      - id: no-commit-to-branch
        args:
          [
            "--pattern",
            '^(?!((fix|feat|hotfix|merge|release)\/[a-zA-Z0-9\-]+)$).*',
          ]
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"
  - repo: https://github.com/grimwm/pre-commit-jvm
    rev: v0.5.2
    hooks:
      - id: google-java-format
        args: [--aosp]
